logging:
    level: "INFO"
    path: "records.log"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    encoding: "utf-8"

gui:
    window_title: "Face Mesh Pro - Modular & Beauty"
    window_width: 1000
    window_height: 800
    initial_text: "Press 'Start' to open camera."

face-mesh:
    width: 640
    height: 480
    print_landmarks: false
    model_path: "models/face_landmarker.task"
    initial_max_faces: 2
    draw_on_left: true
    draw_mode: "mesh"

beauty:
    initial_saturation: 1.0
    initial_sharpness: 0.0
    initial_smoothing: 0
    initial_brighten: 1.0